services:
  warden:
    container_name: warden
    image: warden:latest
    build:
      context: .
      dockerfile: warden.Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
        - app-network
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  demo-app:
    container_name: demo-app
    build:
      context: ./demo-app
      dockerfile: Dockerfile
    image: demo-app:latest
    environment:
      MODE: normal
    networks:
      - app-network
    restart: always

#  demo-worker:
  demo-db:
    image: postgres:15.1-alpine
    container_name: demo-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEMO}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEMO}
      POSTGRES_DB: ${POSTGRES_DB_DEMO}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_demo:/var/lib/postgresql/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app-network
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    networks:
      - app-network
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - app-network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana-provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - app-network

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_demo:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local