name: wardenci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install -r requirements-dev.txt

      - name: Run ruff
        run: ruff check .

      - name: Run Ruff formatter check
        run: ruff format --check .

